language: node_js
node_js:
    - 'stable'
addons:
    apt:
        packages:
            - build-essential
            - ruby
            - ruby-dev
before_install:
    - export GEM_HOME=$HOME/gems
    - gem install --no-ri --no-rdoc fpm
    - export PATH=$PATH:$GEM_HOME/bin
install:
    - npm run setup
script:
    - npm run build
    # Disable FPM script for now
    # - npm run linux
